# Generated by Django 5.0.7 on 2024-07-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stroller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('title_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('stroller_photo_1', models.ImageField(upload_to='stroller_photo')),
                ('stroller_photo_2', models.ImageField(upload_to='stroller_photo')),
                ('stroller_photo_3', models.ImageField(upload_to='stroller_photo')),
                ('stroller_photo_4', models.ImageField(upload_to='stroller_photo')),
                ('stroller_photo_5', models.ImageField(upload_to='stroller_photo')),
                ('stroller_photo_6', models.ImageField(upload_to='stroller_photo')),
                ('stroller_photo_7', models.ImageField(upload_to='stroller_photo')),
                ('stroller_photo_8', models.ImageField(upload_to='stroller_photo')),
                ('stroller_color_1', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_2', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_3', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_4', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_5', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_6', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_7', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_8', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_9', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_10', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_11', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_12', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_13', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_14', models.ImageField(upload_to='stroller_color')),
                ('stroller_color_15', models.ImageField(upload_to='stroller_color')),
                ('features', models.TextField()),
                ('weight_cradle', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight_walking_unit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight_frame_with_wheels', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('width_frame', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
