# Generated by Django 5.0.7 on 2024-07-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='description',
            field=models.TextField(verbose_name='Опис коляски'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='features',
            field=models.TextField(verbose_name='Харакеристики'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='model_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Назва моделі'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Не редагувати!'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='title_name',
            field=models.CharField(max_length=150, verbose_name='Назва заголовку'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редагування'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='weight_cradle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вага люльки'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='weight_frame_with_wheels',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вага рами з колесами'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='weight_walking_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вага прогулянкового блоку'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='width_frame',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ширина рами'),
        ),
    ]
