# Generated by Django 5.0.7 on 2024-07-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroller', '0002_alter_stroller_created_at_alter_stroller_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stroller',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Коляски', 'verbose_name_plural': 'Коляски'},
        ),
    ]
