# Generated by Django 5.0.7 on 2024-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroller', '0003_alter_stroller_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_1',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_10',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_11',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_12',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_13',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_14',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_15',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_2',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_3',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_4',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_5',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_6',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_7',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_8',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_color_9',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_color'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_photo'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_photo'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_photo'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_photo'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_photo'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_photo'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='stroller_photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_photo'),
        ),
    ]
