# Generated by Django 5.0.7 on 2024-07-28 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroller', '0004_alter_stroller_stroller_color_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroller',
            name='features',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
