# Generated by Django 5.0.7 on 2024-07-28 16:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroller', '0005_alter_stroller_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroller',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
