# Generated by Django 5.0.7 on 2024-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroller', '0006_alter_stroller_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stroller',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_photo'),
        ),
    ]
