# Generated by Django 5.0.7 on 2024-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroller', '0007_stroller_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stroller',
            name='featured_photo',
            field=models.ImageField(blank=True, null=True, upload_to='stroller_photo'),
        ),
        migrations.AddField(
            model_name='stroller',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
