# Generated by Django 3.2 on 2024-08-05 13:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroller', '0010_auto_20240805_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stroller',
            name='description_first',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Перший опис'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='description_fourth',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Четвертий опис'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='description_second',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Другий опис'),
        ),
        migrations.AlterField(
            model_name='stroller',
            name='description_third',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Третій опис'),
        ),
    ]
