# Generated by Django 3.2 on 2024-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroller', '0011_auto_20240805_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='stroller',
            name='gallery_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='gallety_photo', verbose_name='Фото для галереї'),
        ),
        migrations.AddField(
            model_name='stroller',
            name='gallery_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='gallety_photo', verbose_name='Фото для галереї'),
        ),
        migrations.AddField(
            model_name='stroller',
            name='gallery_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='gallety_photo', verbose_name='Фото для галереї'),
        ),
        migrations.AddField(
            model_name='stroller',
            name='gallery_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='gallety_photo', verbose_name='Фото для галереї'),
        ),
        migrations.AddField(
            model_name='stroller',
            name='gallery_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='gallety_photo', verbose_name='Фото для галереї'),
        ),
        migrations.AddField(
            model_name='stroller',
            name='gallery_photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='gallety_photo', verbose_name='Фото для галереї'),
        ),
        migrations.AddField(
            model_name='stroller',
            name='gallery_photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='gallety_photo', verbose_name='Фото для галереї'),
        ),
        migrations.AddField(
            model_name='stroller',
            name='gallery_photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='gallety_photo', verbose_name='Фото для галереї'),
        ),
    ]
