services:
  django:
    container_name: django
    image: django-app:7
    ports: 
      - '8000:8000'
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - django